services:
  voip-gatekeeper:
    build:
      context: .
    image: voip-gatekeeper:local
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      TELNYX_PUBLIC_KEY_BASE64: ${TELNYX_PUBLIC_KEY_BASE64}
      CALL_FORWARD_DESTINATION_TYPE: ${CALL_FORWARD_DESTINATION_TYPE}
      CALL_FORWARD_NUMBER: ${CALL_FORWARD_NUMBER}
      CALL_FORWARD_SIP_URI: ${CALL_FORWARD_SIP_URI}
      CALL_FORWARD_SIP_FALLBACK_TO_VOICEMAIL: ${CALL_FORWARD_SIP_FALLBACK_TO_VOICEMAIL}
      CALL_FORWARD_SIP_TIMEOUT_SECONDS: ${CALL_FORWARD_SIP_TIMEOUT_SECONDS}
